# Generated by Django 4.1.3 on 2022-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('num_students_nearby', models.IntegerField(default=0)),
                ('beacon_minor', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_identifier', models.CharField(max_length=200)),
                ('beacon_minor_closest_to', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
