# Generated by Django 4.1.3 on 2022-12-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor', models.IntegerField()),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='beacon_minor',
        ),
    ]
