# Generated by Django 4.1.3 on 2022-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0003_buildingmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position_x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='position_y',
            field=models.FloatField(default=None, null=True),
        ),
    ]
