# Generated by Django 4.1.3 on 2022-12-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0004_student_position_x_student_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_reported_status',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
