# Generated by Django 4.1.3 on 2022-12-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0005_student_user_reported_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='position_x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='position_y',
            field=models.FloatField(default=None, null=True),
        ),
    ]
