# Generated by Django 4.1.3 on 2022-11-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panic',
            name='panic_type',
            field=models.CharField(default='other', max_length=200),
            preserve_default=False,
        ),
    ]
