# Generated by Django 4.1.3 on 2022-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='emergency_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
